### ISSUE TITLE
CSS, SASS, React, Javascript etc. should be checkboxes not select options

### ISSUE THREAD

**Issue by alex-page** [govau/furnace#6]
As a user I should be able to download all the code instead of two libraries.

**Comment by azerella** [comment]
This doesn't seem to be an issue anymore as the component selections are indeed checkboxes:

![image](https://user-images.githubusercontent.com/1501560/55601891-ca366800-57ae-11e9-8c51-90ff2bd4bab4.png)

We've also recently added a `Select all` button, a user can download all the minified css/js they want
