### ISSUE TITLE
Create a log file for use in cloud environments

### ISSUE THREAD

**Issue by alex-page** [govau/furnace#7]

**Comment by pattyde** [comment]
Hey @alex-page, can you please provide a bit more information about the details for this issue?

**Comment by alex-page** [comment]
This is for debugging and seeing when furnace fails or dies. However i'm not sure how this would work when we rebuild our instance every time we deploy on circle. Unless it's just a log file for the current instance.

**Comment by alex-page** [comment]
Closing this issue, if we have problems in the future I will re open this and we can figure out a way to log anything useful then.
